export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
// COURSE
export const COURSE_MODEL = 'COURSE_MODEL';
export const COURSE_LESSON_MODEL = 'COURSE_LESSON_MODEL';
export const COURSE_VIDEO_MODEL = 'COURSE_VIDEO_MODEL';
export const COURSE_ORDER_MODEL = 'COURSE_ORDER_MODEL';
// EXAM
export const EXAM_MODEL = 'EXAM_MODEL';
export const EXAM_LESSON_MODEL = 'EXAM_LESSON_MODEL';
export const EXAM_QUESTION_MODEL = 'EXAM_QUESTION_MODEL';
export const EXAM_HISTORY_MODEL = 'EXAM_HISTORY_MODEL';
// USER
export const USER_MODEL = 'USER_MODEL';
export const FEEDBACK_MODEL = 'FEEDBACK_MODEL';
export const BLOG_MODEL = 'BLOG_MODEL';
export const CONTACT_MODEL = 'CONTACT_MODEL';
export const CATEGORY_MODEL = 'CATEGORY_MODEL';

